# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [22]:
import pandas as pd

url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
df_car = pd.read_csv(url)

In [23]:
df_car.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [24]:
df_car.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [25]:
#To ensure consistency and ease of use, standardize the column names of the dataframe. 
# Start by taking a first look at the dataframe and identifying any column names that need to be modified. 
# Use appropriate naming conventions and make sure that column names are descriptive and informative.
df_car.columns = [ 'customer', 'state', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium', 'number_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']
df_car.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium,number_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [26]:
df_car['policy_type'].unique()

array(['Personal Auto', 'Corporate Auto', 'Special Auto', nan],
      dtype=object)

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [27]:
df_car.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium', 'number_open_complaints', 'policy_type',
       'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [28]:
#check which unique entries there are
df_car.gender.unique()

#make a dictionary for a map
gender_mapping = {"female": "female", "F":"female", "Femal":"female", "f": "female", "M" : "male", "Male" : "male"}

#use map
df_car["gender"] = df_car["gender"].replace(gender_mapping)

display(df_car["gender"].unique)

<bound method Series.unique of 0          NaN
1       female
2       female
3         male
4         male
         ...
4003       NaN
4004       NaN
4005       NaN
4006       NaN
4007       NaN
Name: gender, Length: 4008, dtype: object>

In [29]:
df_car.state.unique()

#make a dictionary for a map
state_mapping = {"AZ": "Arizona", "WA":"Washington", "Cali":"California"}
df_car["state"] = df_car["state"].replace(state_mapping)
display(df_car["state"].unique())

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [30]:
df_car.education.unique()
#make a dictionary for a map
education_mapping = {"Bachelors": "Bachelor"}
df_car["education"] = df_car["education"].replace(education_mapping)
display(df_car["education"].unique())

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [31]:
df_car.customer_lifetime_value.unique()
df_car.customer_lifetime_value = df_car.customer_lifetime_value.str.strip('%')
display(df_car.customer_lifetime_value.unique())

array([nan, '697953.59', '1288743.17', ..., '2031499.76', '323912.47',
       '899704.02'], shape=(1028,), dtype=object)

In [32]:
df_car.vehicle_class.unique()
class_mapping = {"Luxury SUV": "Luxury", "Luxury Car":"Luxury", "Sports Car":"Luxury"}
df_car["vehicle_class"] = df_car["vehicle_class"].replace(class_mapping)
display(df_car["vehicle_class"].unique())

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [33]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer                 1071 non-null   object
 1   state                    1071 non-null   object
 2   gender                   954 non-null    object
 3   education                1071 non-null   object
 4   customer_lifetime_value  1068 non-null   object
 5   income                   1071 non-null   float64
 6   monthly_premium          1071 non-null   float64
 7   number_open_complaints   1071 non-null   object
 8   policy_type              1071 non-null   object
 9   vehicle_class            1071 non-null   object
 10  total_claim_amount       1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [34]:
#check orriginal data type
print(df_car['customer_lifetime_value'].dtype)

object

In [35]:
#change data type to float
df_car['customer_lifetime_value'] = df_car['customer_lifetime_value'].astype(float)
display(df_car['customer_lifetime_value'].dtype)

dtype('float64')

In [36]:
# Check unique values to understand the format better.
print(df_car['number_open_complaints'].unique())

['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]

In [37]:

# Extract the middle value using split and cast to integer.
def extract_middle_value(value):
    if isinstance(value, str):
        parts = value.split('/')  # Split the string by '/'
        return int(parts[1]) if len(parts) > 1 else 0  # Return the middle value if it exists, otherwise return 0.
    else:
        return 0
# Apply the function to convert the entire column.
df_car['number_open_complaints'] = df_car['number_open_complaints'].apply(extract_middle_value)

#test
display(df_car['number_open_complaints'].head())

0    0
1    0
2    0
3    0
4    0
Name: number_open_complaints, dtype: int64

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [38]:
df_car.isnull()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium,number_open_complaints,policy_type,vehicle_class,total_claim_amount
0,False,False,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4003,True,True,True,True,True,True,True,False,True,True,True
4004,True,True,True,True,True,True,True,False,True,True,True
4005,True,True,True,True,True,True,True,False,True,True,True
4006,True,True,True,True,True,True,True,False,True,True,True
4007,True,True,True,True,True,True,True,False,True,True,True

In [39]:
#dropping rows with all null values

# Create a mask for rows that are all NaN except potentially 'number_open_complaints'
#mask_all_null_except_complaints = df_car.drop(columns=['number_open_complaints']).isnull().all(axis=1)

# check results 
#print("Rows that are all NaN except 'number_open_complaints':")
#print(df_car[mask_all_null_except_complaints])

# Update 'Number of Open Complaints' from 0 to NaN in these identified rows
#df_car.loc[mask_all_null_except_complaints, 'number_open_complaints'] = \
#    df_car.loc[mask_all_null_except_complaints, 'number_open_complaints'].replace(0, np.nan)

#Print the DataFrame after changes to check
#print("DataFrame after replacing 0 with NaN in 'number_open_complaints':")
#print(df_car)

# Now you can safely drop all NaN rows
#df_cleaned = df_car.dropna(how='all')

# Check the cleaned DataFrame
#print("Cleaned DataFrame:")
#df_cleaned
#copy to original file
#df_car = df_cleaned

In [40]:
df_car.vehicle_class.unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

In [41]:
df_car['number_open_complaints'].unique()

array([0, 2, 1, 3, 5, 4])

In [42]:

null_counts = df_car['number_open_complaints'].isnull().unique()
df_car.loc[:,'state'] = df_car['state'].fillna('Unknown')
df_car.loc[:,'customer'] = df_car['customer'].fillna('Invalid')
df_car.loc[:,'gender'] = df_car['gender'].fillna('divers')
df_car.loc[:,'education'] = df_car['education'].fillna('Unknown')
df_car.loc[:,'policy_type'] = df_car['policy_type'].fillna('Invalid')

In [43]:
# filling in customer_lifetime_value with mean of customers with same vehicle_class
#make function (nested if statements)
def fill_missing_customer_life_value(row):
    if pd.isnull(row['customer_lifetime_value']):
        if row['vehicle_class'] == 'Luxury':
            return luxury_mean_income
        elif row['vehicle_class'] == 'Four-Door Car':
            return four_door_mean_income
        elif row['vehicle_class'] == 'SUV':
            return suv_mean_income
        elif row['vehicle_class'] == 'Two-Door Car':
            return two_door_mean_income
    return row['customer_lifetime_value']
#seperate the data
luxury_df = df_car[df_car['vehicle_class'] == 'Luxury']
four_door_df = df_car[df_car['vehicle_class'] == 'Four-Door Car']
two_door_df = df_car[df_car['vehicle_class'] == 'Two-Door Car']
suv_df = df_car[df_car['vehicle_class'] == 'SUV']

#calculate mean incomes
luxury_mean_income = luxury_df['customer_lifetime_value'].mean()
four_door_mean_income = four_door_df['customer_lifetime_value'].mean()
two_door_mean_income = two_door_df['customer_lifetime_value'].mean()
suv_mean_income = suv_df['customer_lifetime_value'].mean()

#call function
df_car['customer_lifetime_value'] = df_car.apply(fill_missing_customer_life_value, axis=1)

In [44]:
# filling in income with mean of customers with same vehicle_class
#make function (nested if statements)
def fill_missing_income(row):
    if pd.isnull(row['income']):
        if row['vehicle_class'] == 'Luxury':
            return luxury_mean_income
        elif row['vehicle_class'] == 'Four-Door Car':
            return four_door_mean_income
        elif row['vehicle_class'] == 'SUV':
            return suv_mean_income
        elif row['vehicle_class'] == 'Two-Door Car':
            return two_door_mean_income
    return row['income']
#seperate the data
luxury_df = df_car[df_car['vehicle_class'] == 'Luxury']
four_door_df = df_car[df_car['vehicle_class'] == 'Four-Door Car']
two_door_df = df_car[df_car['vehicle_class'] == 'Two-Door Car']
suv_df = df_car[df_car['vehicle_class'] == 'SUV']

#calculate mean incomes
luxury_mean_income = luxury_df['income'].mean()
four_door_mean_income = four_door_df['income'].mean()
two_door_mean_income = two_door_df['income'].mean()
suv_mean_income = suv_df['income'].mean()

#call function
df_car['income'] = df_car.apply(fill_missing_income, axis=1)

display(df_car.head(10))

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium,number_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,divers,Master,6.697018e+05,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,female,Bachelor,6.979536e+05,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,female,Bachelor,1.288743e+06,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,male,Bachelor,7.645862e+05,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,male,High School or Below,5.363077e+05,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,female,Bachelor,8.256298e+05,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,female,College,5.380899e+05,55350.0,67.0,0,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,male,Master,7.216100e+05,0.0,101.0,0,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,male,Bachelor,2.412750e+06,14072.0,71.0,0,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,female,College,7.388178e+05,28812.0,93.0,0,Special Auto,Four-Door Car,425.527834

In [45]:
#filling missing values total_claim_amount with the mean of the total_claim_amount of customers with the same number of open complaints
#group open_complaints
group_means = df_car.groupby('number_open_complaints')['total_claim_amount'].transform('mean')
#fill missing values
df_car['total_claim_amount'] = df_car['total_claim_amount'].fillna(group_means)
df_car.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium,number_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,divers,Master,6.697018e+05,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,female,Bachelor,6.979536e+05,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,female,Bachelor,1.288743e+06,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,male,Bachelor,7.645862e+05,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,male,High School or Below,5.363077e+05,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [46]:
df_car.duplicated().unique()
#which rows are duplicated?
duplicates = df_car.duplicated()

# Filter to show only duplicates, keep=False marks all instances of duplicates
duplicate_rows = df_car[duplicates]

# Display the duplicate rows
print("Duplicate Rows:\n", duplicate_rows)

Duplicate Rows:
      customer    state  gender education  customer_lifetime_value  income  \
1072  Invalid  Unknown  divers   Unknown                      NaN     NaN
1073  Invalid  Unknown  divers   Unknown                      NaN     NaN
1074  Invalid  Unknown  divers   Unknown                      NaN     NaN
1075  Invalid  Unknown  divers   Unknown                      NaN     NaN
1076  Invalid  Unknown  divers   Unknown                      NaN     NaN
...       ...      ...     ...       ...                      ...     ...
4003  Invalid  Unknown  divers   Unknown                      NaN     NaN
4004  Invalid  Unknown  divers   Unknown                      NaN     NaN
4005  Invalid  Unknown  divers   Unknown                      NaN     NaN
4006  Invalid  Unknown  divers   Unknown                      NaN     NaN
4007  Invalid  Unknown  divers   Unknown                      NaN     NaN

      monthly_premium  number_open_complaints policy_type vehicle_class  \
1072              NaN                       0     Invalid           NaN
1073              NaN                       0     Invalid           NaN
1074              NaN                       0     Invalid           NaN
1075              NaN                       0     Invalid           NaN
1076              NaN                       0     Invalid           NaN
...               ...                     ...         ...           ...
4003              NaN                       0     Invalid           NaN
4004              NaN                       0     Invalid           NaN
4005              NaN                       0     Invalid           NaN
4006              NaN                       0     Invalid           NaN
4007              NaN                       0     Invalid           NaN

      total_claim_amount
1072           407.51201
1073           407.51201
1074           407.51201
1075           407.51201
1076           407.51201
...                  ...
4003           407.51201
4004           407.51201
4005           407.51201
4006           407.51201
4007           407.51201

[2936 rows x 11 columns]

None of the duplicated rows contain any relevant or usable data. So they can all be deleted

In [47]:
#remove duplicated rows bades on all columns
df_car_unique = df_car.drop_duplicates(keep= False)

display(df_car_unique.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
1066    False
1067    False
1068    False
1069    False
1070    False
Length: 1071, dtype: bool

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [48]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from data_cleaning import clean_data

# Load your data
df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')

# Clean your data
df_cleaned = clean_data(df)

# Preview cleaned data
df.head(20)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium,number_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Divers,Master,6.697018e+05,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,6.979536e+05,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1.288743e+06,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,7.645862e+05,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,5.363077e+05,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,8.256298e+05,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,5.380899e+05,55350.0,67.0,0,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,7.216100e+05,0.0,101.0,0,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2.412750e+06,14072.0,71.0,0,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,7.388178e+05,28812.0,93.0,0,Special Auto,Four-Door Car,425.527834
10,SX51350,California,M,College,4.738992e+05,0.0,67.0,0,Personal Auto,Four-Door Car,482.400000
11,VQ65197,California,Divers,College,8.197197e+05,0.0,110.0,0,Personal Auto,SUV,528.000000
12,DP39365,California,Divers,Master,8.798797e+05,77026.0,110.0,2,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,Divers,High School or Below,8.819019e+05,99845.0,110.0,1,Corporate Auto,SUV,528.000000
14,IL66569,California,Divers,College,5.384432e+05,83689.0,70.0,2,Corporate Auto,Four-Door Car,307.139132
15,BW63560,Oregon,Divers,Bachelor,7.463139e+05,24599.0,64.0,1,Corporate Auto,Four-Door Car,42.920271
16,FV94802,Nevada,Divers,High School or Below,2.566868e+05,25049.0,67.0,0,Personal Auto,Two-Door Car,454.245098
17,OE15005,Cali,Divers,College,3.945242e+05,28855.0,101.0,0,Personal Auto,SUV,647.442031
18,WC83389,Oregon,Divers,College,5.710333e+05,51148.0,72.0,0,Personal Auto,Four-Door Car,308.981664
19,FL50705,California,Divers,High School or Below,8.162617e+05,66140.0,101.0,0,Corporate Auto,Four-Door Car,484.800000

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [49]:
df.describe()

,customer_lifetime_value,income,monthly_premium,number_open_complaints,total_claim_amount
count,1.071000e+03,1071.000000,1071.000000,4008.000000,1071.000000
mean,7.933430e+05,39295.701214,193.234360,0.105289,404.986909
std,6.426091e+05,30469.427060,1601.190369,0.488849,293.027260
min,2.004351e+05,0.000000,61.000000,0.000000,0.382107
25%,4.048535e+05,14072.000000,68.000000,0.000000,202.157702
50%,5.887182e+05,36234.000000,83.000000,0.000000,354.729129
75%,8.945210e+05,64631.000000,109.500000,0.000000,532.800000
max,5.816655e+06,99960.000000,35354.000000,5.000000,2893.239678

In [56]:

from data_cleaning import clean_data 
raw_df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')

# Apply the cleaning process defined in your .py file
df_cleaned = clean_data(raw_df)

# Ensure the data is cleaned 
print("Column names in Cleaned DataFrame:", df_cleaned.columns)

# Set correct column names using the cleaned data
total_claim_col = 'total_claim_amount'  # Confirm this matches your current cleaned data setup
customer_lifetime_col = 'customer_lifetime_value'

# Calculate percentiles
claim_75th_percentile = df_cleaned[total_claim_col].quantile(0.75)
clv_25th_percentile = df_cleaned[customer_lifetime_col].quantile(0.25)

# Filter for high claim and low CLV
filtered_df = df_cleaned[
    (df_cleaned[total_claim_col] > claim_75th_percentile) &
    (df_cleaned[customer_lifetime_col] < clv_25th_percentile)
]

# Get summary statistics
summary_stats = filtered_df[[total_claim_col, customer_lifetime_col]].describe()

# Output the results
print("Summary statistics for customers with high policy claim and low CLV:")
print(summary_stats)

Column names in Cleaned DataFrame: Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium', 'number_open_complaints', 'policy_type',
       'vehicle_class', 'total_claim_amount'],
      dtype='object')
Summary statistics for customers with high policy claim and low CLV:
       total_claim_amount  customer_lifetime_value
count           40.000000                40.000000
mean           723.776577            341577.910000
std            149.280606             56921.472027
min            537.600000            228759.690000
25%            633.378846            304220.875000
50%            685.284189            365995.370000
75%            799.200000            387364.700000
max           1185.988301            402381.440000